// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfksqtwmrxeuhgrmsmfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRma3NxdHdtcnhldWhncm1zbWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjQwNzQsImV4cCI6MjA2OTEwMDA3NH0.EJuAnF6H-9bsLiRROCAykdhcaIfntK12f6-ZzMDA0g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});